---
machine_name: envdep-example

main_hostname: envdep-example.com
main_dir: "/var/www/{{ main_hostname }}"
main_docroot: "public"

timezone: 'America/New_York'

# The web server software to be used. Options: 'apache', 'nginx'.
webserver: 'nginx'

# The database software to be used. Options: 'mysql', 'mariadb'.
dbserver: 'mysql'

nginx_vhosts:
#Example vhost below, showing all available options:
- listen: "443 ssl http2 default_server"
  server_name: "www.{{ main_hostname }}"
  server_name_redirect: "{{ main_hostname }}"
  root: "{{ main_dir }}/{{ main_docroot }}"
  index: "index.php index.html index.htm"
  filename: "{{ main_hostname }}.conf"
  access_log: "/var/log/nginx/{{ main_hostname }}_access.log"
  error_log: "/var/log/nginx/{{ main_hostname }}_error.log"
  ssl_certificate: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
  ssl_certificate_key: "/etc/ssl/private/ssl-cert-snakeoil.key"
  state: "present"

mysql_version: '8.0'
mariadb_version: '10.5'

mysql_root_password: root
mysql_databases:
  - name: "envdep_example_db"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "envdep_example_user"
    host: "%"
    password: "test"
    priv: "envdep_example_db.*:ALL"

extra_software:
  - adminer
  - mailhog
  - nodejs
  - postfix
  - xdebug

php_version: '8.0'
php_packages_extra:
  - "php{{ php_version }}-fpm"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

adminer_theme: 'pepa-linha'

composer_version: 2

nodejs_version: "10.x"

php_xdebug_version: "3.0.4"

extra_packages:
  - build-essential
