---
# Gather configuration
- name: Define config_dir
  set_fact:
    config_dir: "{{ lookup('env', 'ENVDEP_CONFIG_DIR') }}"

- name: Define env
  set_fact:
    env: " {{ lookup('env', 'ENVDEP_ENV') }}"

- name: Define config
  include_tasks: "{{ item }}"
  with_fileglob:
    - "{{ config_dir }}/config.yml"
    - "{{ config_dir }}/secrets.yml"
    - "{{ config_dir }}/environments/{{ env }}/config.yml"
    - "{{ config_dir }}/environments/{{ env }}/secrets.yml"
