---
- hosts: localhost

  vars_files:
    - ../default.config.yml
    - "{{ lookup('env', 'ENVDEP_CONFIG_DIR') }}/secrets.yml"
    - "{{ lookup('env', 'ENVDEP_CONFIG_DIR') }}/config.yml"

  pre_tasks:
    - set_fact:
        ddev: true
    - import_tasks: tasks/config.yml
      tags: ['always']

  roles:
    - role: ddev
