---
roles:
  - name: geerlingguy.adminer
    version: "1.3.0"
  - name: geerlingguy.apache
    version: "3.1.4"
  - name: geerlingguy.apache-php-fpm
    version: "1.1.0"
  - name: geerlingguy.composer
    version: "1.9.0"
  - name: geerlingguy.git
    version: "3.0.0"
  - name: geerlingguy.mailhog
    version: "2.2.0"
  - name: geerlingguy.mysql
    version: "3.3.0"
  - name: geerlingguy.nginx
    version: "3.0.0"
  - name: geerlingguy.nodejs
    version: "5.1.1"
  - name: geerlingguy.php
    version: "4.5.1"
  - name: geerlingguy.php-mysql
    version: "2.1.0"
  - name: geerlingguy.php-versions
    version: "5.0.0"
  - name: geerlingguy.php-xdebug
    version: "3.0.0"
  - name: geerlingguy.postfix
    version: "2.0.0"
